// Copyright (c) 2024-present Sphinx Core Dev
// MIT License https://opensource.org/license/mit

// go/src/crypto/STHINCS/sthincs/golden_test.go
package sthincs

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sync"
	"testing"

	"github.com/sphinxfndorg/protocol/src/crypto/STHINCS/address"
	"github.com/sphinxfndorg/protocol/src/crypto/STHINCS/hypertree"
	"github.com/sphinxfndorg/protocol/src/crypto/STHINCS/parameters"
	"github.com/sphinxfndorg/protocol/src/crypto/STHINCS/xmss"
)

// This file is the byte-identity harness for the signing-path optimizations
// (parallel tree building, reusing the root that the build already computed,
// FORS parallelism, and per-hash allocation cuts).
//
// Every one of those changes is supposed to be invisible in the signature
// bytes: same keys and same message must produce the same serialized
// signature, for every backend and variant, or a node running the new code
// and a node running the old code disagree about the same signature.
//
// The signatures below were generated by the PRE-optimization implementation
// and are asserted as literals. A mismatch means the optimization changed the
// output, which is a consensus-level change and must fail loudly rather than
// ship.
//
// RANDOMIZE=false is required: with randomization on, Spx_sign reads fresh
// entropy for OptRand, so no signature is reproducible.

// fixedKey builds a deterministic secret key from a label, so the golden
// vectors depend only on this test file and the construction — never on
// crypto/rand.
func fixedKey(t *testing.T, params *parameters.Parameters, label string) (*SPHINCS_SK, *SPHINCS_PK) {
	t.Helper()
	derive := func(tag string) []byte {
		sum := sha256.Sum256([]byte("sthincs-golden/" + label + "/" + tag))
		return sum[:params.N]
	}
	SKseed := derive("SKseed")
	SKprf := derive("SKprf")
	PKseed := derive("PKseed")

	PKroot, err := hypertree.Ht_PKgen(params, SKseed, PKseed)
	if err != nil {
		t.Fatalf("Ht_PKgen: %v", err)
	}
	sk := &SPHINCS_SK{SKseed: SKseed, SKprf: SKprf, PKseed: PKseed, PKroot: PKroot}
	pk := &SPHINCS_PK{PKseed: PKseed, PKroot: PKroot}
	return sk, pk
}

// goldenSignatures pins the pre-optimization signature bytes, captured from
// the sequential implementation before any of the signing-path changes landed.
//
// Format: "<set> <serialized length> <sha256 of serialized signature>".
// A mismatch here means the signature bytes changed, which is a
// consensus-level break: a node on the new code and a node on the old code
// would disagree about the same signature. Re-baseline ONLY for an
// intentional protocol change.
//
// RE-BASELINE (SPHINXHASH rows only): the three SPHINXHASH-* digests below were
// regenerated when the spxhash/v2 branch-`A` primitive changed from a double
// SHA-256 to a single SHA-512/256 (see src/spxhash/v2/README.md, "Changed
// (branch A)"). Only the SPHINXHASH backend routes through spxhash/v2, so the
// SHA256-* and SHAKE256-* digests are unchanged. Signature *lengths* are
// unchanged; only the bytes moved. This is the deliberate, documented protocol
// change permitted by the paragraph above.
var goldenSignatures = map[string]struct {
	Len       int
	SigSHA256 string
}{
	"SHA256-128f-simple":     {7216, "3301b7525d1f09c6fa67a72e12f28a49521de1b818d1681dbc3a03e557b3db28"},
	"SHA256-128f-robust":     {7216, "f8fa282be616272541e85845e324853bf2d984aebc3bd632ec77bf0f87c2d3d8"},
	"SHA256-128s-simple":     {4864, "f6f21a97664e95258abeb60ef8e2c897102b2fea2340850adb7fddf55857e57c"},
	"SHA256-192f-simple":     {15216, "9193e4ec2c175b971304fda0eefac8fbda2d3ba6ed8e03b8944f69fec5518a1c"},
	"SHAKE256-128f-simple":   {7216, "1b1b66857ceaf46040edeb66b134e18287a917ea4245bc3337e5c8dbab4d468a"},
	"SHAKE256-128f-robust":   {7216, "f4f878771ecfb82ad3a4fb440da49f92fdfb49371e0bd8c05d51f10bcf9cb8c9"},
	"SPHINXHASH-128f-simple": {7216, "08401a244e6f9f43149f0aff8a68b44798fe13d8944b5f77ea413175267db9d1"},
	"SPHINXHASH-128f-robust": {7216, "2c3a56284907c76c8abb5db182431a4d3c6d06faf6df2d5928ed3145bd7870b0"},
	"SPHINXHASH-192f-robust": {15216, "e82c565bcbd217118c67e05c0f8378b20df5b97ff01426efd8297c6a4099eb6c"},
}

// TestGoldenSignatures pins the signature bytes for every backend.
//
// The parallel tree build, the reuse of the root the build already computed,
// FORS parallelism and the per-hash allocation cuts are all required to be
// invisible here. If one of them is not, this fails.
func TestGoldenSignatures(t *testing.T) {
	constructors := []struct {
		name string
		make func(bool) *parameters.Parameters
	}{
		{"SHA256-128f-simple", parameters.MakeSthincsPlusSHA256128fSimple},
		{"SHA256-128f-robust", parameters.MakeSthincsPlusSHA256128fRobust},
		{"SHA256-128s-simple", parameters.MakeSthincsPlusSHA256128sSimple},
		{"SHA256-192f-simple", parameters.MakeSthincsPlusSHA256192fSimple},
		{"SHAKE256-128f-simple", parameters.MakeSthincsPlusSHAKE256128fSimple},
		{"SHAKE256-128f-robust", parameters.MakeSthincsPlusSHAKE256128fRobust},
		{"SPHINXHASH-128f-simple", parameters.MakeSthincsPlusSPHINXHASH128fSimple},
		{"SPHINXHASH-128f-robust", parameters.MakeSthincsPlusSPHINXHASH128fRobust},
		{"SPHINXHASH-192f-robust", parameters.MakeSthincsPlusSPHINXHASH192fRobust},
	}

	msg := []byte("sthincs-golden-signature")

	for _, tc := range constructors {
		t.Run(tc.name, func(t *testing.T) {
			want, ok := goldenSignatures[tc.name]
			if !ok {
				t.Fatalf("no golden vector pinned for %s", tc.name)
			}
			params := tc.make(false) // RANDOMIZE=false: reproducible bytes
			sk, pk := fixedKey(t, params, tc.name)

			sig, err := Spx_sign(params, msg, sk)
			if err != nil {
				t.Fatalf("Spx_sign: %v", err)
			}
			raw, err := sig.SerializeSignature()
			if err != nil {
				t.Fatalf("SerializeSignature: %v", err)
			}
			if !Spx_verify(params, msg, sig, pk) {
				t.Fatal("golden signature failed to verify")
			}
			if len(raw) != want.Len {
				t.Errorf("signature length = %d, want %d", len(raw), want.Len)
			}
			sum := hex.EncodeToString(func() []byte { s := sha256.Sum256(raw); return s[:] }())
			if sum != want.SigSHA256 {
				t.Errorf("signature bytes changed for %s\n  got  %s\n  want %s\n"+
					"This is a consensus-breaking change: nodes running different code would\n"+
					"disagree about the same signature. Revert the change, or re-baseline\n"+
					"deliberately if the protocol is meant to change.",
					tc.name, sum, want.SigSHA256)
			}
		})
	}
}

// TestTopTreeCacheIsValidatedAgainstTheKey checks the one place the top-layer
// cache could go wrong: if the key's seeds change (or are zeroed) without the
// cache being rebuilt, signing would use a root that no longer matches the
// seeds. The cache must be discarded and rebuilt rather than trusted.
func TestTopTreeCacheIsValidatedAgainstTheKey(t *testing.T) {
	params := parameters.MakeSthincsPlusSHA256128fSimple(false)
	sk, pk := fixedKey(t, params, "cache-validation")
	msg := []byte("cache-validation")

	// First sign populates the cache and must succeed.
	if _, err := Spx_sign(params, msg, sk); err != nil {
		t.Fatalf("Spx_sign (cold cache): %v", err)
	}
	if sk.topTree == nil {
		t.Fatal("expected the top layer to be cached after the first signature")
	}

	// A corrupted cache must not be trusted: force the cached root to differ
	// from PKroot and confirm signing still works, because topTreeFor
	// revalidates against the key's own seeds.
	sk.mu.Lock()
	sk.topTree = corruptedTreeCache(params)
	sk.mu.Unlock()

	sig, err := Spx_sign(params, msg, sk)
	if err != nil {
		t.Fatalf("Spx_sign with a stale cache: %v", err)
	}
	if !Spx_verify(params, msg, sig, pk) {
		t.Fatal("signature made with a rebuilt cache did not verify")
	}

	// Zeroize must release the cache: the key is spent.
	sk.Zeroize()
	if sk.topTree != nil {
		t.Error("Zeroize left the top-layer cache populated")
	}
}

// corruptedTreeCache returns a cache whose root does not match the key, to
// exercise the revalidation path in topTreeFor.
func corruptedTreeCache(params *parameters.Parameters) *xmss.Xmss_treeCache {
	adrs := new(address.ADRS)
	adrs.SetLayerAddress(params.D - 1)
	adrs.SetTreeAddress(0)
	c, err := xmss.Xmss_cacheLeaves(params, make([]byte, params.N), make([]byte, params.N), adrs)
	if err != nil {
		panic(err)
	}
	return c
}

// TestConcurrentSigningOnOneKey exercises signing from several goroutines with
// the same SPHINCS_SK, which the top-layer cache has to tolerate: the cache is
// lazily populated and then shared, so populating it twice concurrently is a
// data race unless it is guarded.
//
// Run under -race for this to be worth anything.
func TestConcurrentSigningOnOneKey(t *testing.T) {
	for _, ctor := range []func(bool) *parameters.Parameters{
		parameters.MakeSthincsPlusSHA256128fSimple,
		parameters.MakeSthincsPlusSHA256128fRobust,
		parameters.MakeSthincsPlusSHAKE256128fRobust,
		parameters.MakeSthincsPlusSPHINXHASH128fSimple,
		parameters.MakeSthincsPlusSPHINXHASH128fRobust,
	} {
		params := ctor(false)
		sk, pk := fixedKey(t, params, "concurrent")

		const goroutines = 8
		var wg sync.WaitGroup
		errCh := make(chan error, goroutines)
		for i := 0; i < goroutines; i++ {
			wg.Add(1)
			go func(i int) {
				defer wg.Done()
				// Distinct messages, so a mix-up between goroutines would
				// produce a signature that does not verify.
				msg := fmt.Appendf(nil, "concurrent-probe-%d", i)
				sig, err := Spx_sign(params, msg, sk)
				if err != nil {
					errCh <- fmt.Errorf("goroutine %d: Spx_sign: %w", i, err)
					return
				}
				if !Spx_verify(params, msg, sig, pk) {
					errCh <- fmt.Errorf("goroutine %d: signature did not verify", i)
				}
			}(i)
		}
		wg.Wait()
		close(errCh)
		for err := range errCh {
			t.Error(err)
		}
	}
}

// TestSigningIsDeterministicAndOrderIndependent checks the two properties the
// parallel implementation must preserve, independent of the pinned vectors:
//
//  1. Signing the same message twice yields identical bytes (no map iteration
//     order, no goroutine scheduling, leaking into the output).
//  2. A signature made under a different key does not verify, and vice versa.
func TestSigningIsDeterministicAndOrderIndependent(t *testing.T) {
	for _, ctor := range []func(bool) *parameters.Parameters{
		parameters.MakeSthincsPlusSHA256128fSimple,
		parameters.MakeSthincsPlusSHA256128fRobust,
		parameters.MakeSthincsPlusSHAKE256128fRobust,
		parameters.MakeSthincsPlusSPHINXHASH128fSimple,
		parameters.MakeSthincsPlusSPHINXHASH128fRobust,
	} {
		params := ctor(false)
		sk, pk := fixedKey(t, params, "determinism")
		other, _ := fixedKey(t, params, "determinism-other")

		msg := []byte("determinism-probe")
		a, err := Spx_sign(params, msg, sk)
		if err != nil {
			t.Fatalf("Spx_sign a: %v", err)
		}
		ra, err := a.SerializeSignature()
		if err != nil {
			t.Fatal(err)
		}

		// Repeat several times: with a parallel tree build, a shared
		// non-thread-safe buffer would show up as intermittent corruption,
		// so a single repeat is not enough evidence.
		for i := 0; i < 4; i++ {
			b, err := Spx_sign(params, msg, sk)
			if err != nil {
				t.Fatalf("Spx_sign b (%d): %v", i, err)
			}
			rb, err := b.SerializeSignature()
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(ra, rb) {
				t.Fatalf("signing is not deterministic: repeat %d differs from the first signature", i)
			}
		}

		if !Spx_verify(params, msg, a, pk) {
			t.Fatal("own signature did not verify")
		}
		if Spx_verify(params, msg, a, &SPHINCS_PK{PKseed: other.PKseed, PKroot: other.PKroot}) {
			t.Fatal("signature verified under a different public key")
		}
		if Spx_verify(params, []byte("different message"), a, pk) {
			t.Fatal("signature verified under a different message")
		}
	}
}
