version: "2"

run:
  timeout: 5m

linters:
  disable:
    - errcheck
    - unused
    - depguard
  
  enable:
    - govet
    - gofmt
    - gosimple
    - ineffassign
    - staticcheck
    - unconvert
    - misspell
    - nakedret