// Copyright (c) 2024-present Sphinx Core Dev
// MIT License https://opensource.org/license/mit

// go/src/usi/gui/collection_test.go
package gui

import (
	"os"
	"path/filepath"
	"testing"
)

// TestSavedCollectionPersistence locks in the contract the Mint Data screen's
// deploy-driven collection flow relies on: the contract address GENERATED by a
// deploy is remembered across launches, an absent file means "no collection
// yet" (never an error), the file is private (0600, it lives beside the keys),
// and a corrupt file degrades to the zero value rather than surfacing junk.
func TestSavedCollectionPersistence(t *testing.T) {
	path := filepath.Join(t.TempDir(), "usi_collection.json")

	// Absent file => zero value, no error.
	if got := loadCollectionFrom(path); got.Address != "" {
		t.Fatalf("absent file must load the zero value, got %+v", got)
	}

	want := SavedCollection{
		// Canonical SPIF display form — "SPIF " + 16 groups of 4 uppercase
		// hex (64 hex total), the format a Deploy New Collection now returns
		// from the node. Persistence itself is format-agnostic (the address
		// is stored verbatim, exactly as the node derived it), so legacy
		// addresses saved before the format fix keep round-tripping too.
		Address:    "SPIF 0011 2233 4455 6677 8899 AABB CCDD EEFF 0011 2233 4455 6677 8899 AABB CCDD EEFF",
		Name:       "Datasets",
		Symbol:     "DSC",
		DeployedAt: 1234567890,
	}
	if err := saveCollectionTo(path, want); err != nil {
		t.Fatalf("saveCollectionTo: %v", err)
	}
	if got := loadCollectionFrom(path); got != want {
		t.Fatalf("round-trip mismatch\n got: %+v\nwant: %+v", got, want)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat saved collection: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0600 {
		t.Fatalf("saved collection must be 0600 (it sits beside the keys), got %o", perm)
	}

	// Corrupt file must degrade to the zero value, never junk.
	if err := os.WriteFile(path, []byte("{not json"), 0600); err != nil {
		t.Fatalf("write corrupt file: %v", err)
	}
	if got := loadCollectionFrom(path); got.Address != "" {
		t.Fatalf("corrupt file must load the zero value, got %+v", got)
	}
}
